# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

pod 'AFNetworking', '~> 3.1.0'
pod 'Masonry', '~> 1.0'
pod 'WebViewJavascriptBridge', '~> 5.0'
pod 'MJRefresh'
pod 'SVProgressHUD'
pod 'BabyBluetooth','~> 0.7.0'

target 'iOSBaseDevProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iOSBaseDevProject
  
  target 'iOSBaseDevProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSBaseDevProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
