# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!

target 'iOSBaseDevProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iOSBaseDevProject
  pod 'AFNetworking'
  pod 'Masonry'
  pod 'WebViewJavascriptBridge'
  pod 'MJRefresh'
  pod 'SVProgressHUD'
  
  target 'iOSBaseDevProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSBaseDevProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
